version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01-data:/usr/share/elasticsearch/data
      - ./data:/usr/share/elasticsearch/config/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  kib01:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kib01
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    volumes:
      - kib01-data:/usr/share/elasticsearch/data
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - es01

volumes:
  es01-data:
    driver: local
  kib01-data:
    driver: local

networks:
  elastic:
    driver: bridge
